apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-csi.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-csi.fullname" . }}
subjects:
- apiGroup:
  kind: ServiceAccount
  name: {{ include "cert-manager-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
